name: initial_code
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.1.0
  flutter_slidable: ^2.0.0
  window_manager: ^0.3.7
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  http: ^0.13.5
  flutter_easyloading: ^3.0.5
  lottie: ^2.3.2
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  pdf: ^3.6.4
  printing: ^5.6.5
  open_file: ^3.2.1
  flutter_native_image: ^0.0.6+1
  image_picker: ^1.0.2
  flutter_form_builder: ^7.7.0
  intl: ^0.17.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottie/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf
